server {
    listen 80;
    server_name api.todoastros.com;

    location /api/auth/ {
        proxy_pass http://auth_service:5050/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/zodiac/ {
        proxy_pass http://zodiac_service:5001/zodiac/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/astronomy/ {
        proxy_pass http://astronomy_service:5003/astronomy/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/weather/ {
        proxy_pass http://weather_service:5004/weather/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/openai/ {
        proxy_pass http://openai_service:5010/openai/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/astro_report/ {
        proxy_pass http://astro_report_service:5006/astro_report/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/news/ {
        proxy_pass http://news_service:5007/news/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/pdf/ {
        proxy_pass http://pdf_service:5008/pdf/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/music/ {
        proxy_pass http://music_service:5000/api/music/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/movies/ {
        proxy_pass http://movie_service:5000/api/movies/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://api_gateway:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
