server {
    listen 80;
    server_name todoastros.com www.todoastros.com;  # Reemplaza con tu dominio real
    
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    
    # Configuración para los servicios Python
    location /api/astrology {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    
    # Configuración para archivos estáticos
    location /_next/static {
        alias /var/html/todoastros/frontend/.next/static;
        expires 365d;
        access_log off;
    }
    
    # Configuración para otros servicios si es necesario
    location /api/zodiac {
        proxy_pass http://localhost:5001;
    }
    
    location /api/music {
        proxy_pass http://localhost:5002;
    }
    
    location /api/astronomy {
        proxy_pass http://localhost:5003;
    }
    
    location /api/weather {
        proxy_pass http://localhost:5004;
    }
    
    location /api/astro_report {
        proxy_pass http://localhost:5006;
    }
    
    location /api/news {
        proxy_pass http://localhost:5007;
    }
}

